import { ethers } from "ethers";
import fs from "fs";
import path from "path";

async function main() {
  const provider = new ethers.JsonRpcProvider(process.env.POLYGON_RPC_URL);
  const wallet = new ethers.Wallet(process.env.PRIVATE_KEY!, provider);

  console.log("Deploying contract with the account:", wallet.address);

  // Load the compiled contract JSON (this would normally be generated by Hardhat or similar)
  // For this environment, we'll assume the ABI and Bytecode are available.
  const contractJson = JSON.parse(fs.readFileSync(path.join(__dirname, "BlueCarbonRegistry.json"), "utf8"));
  
  const factory = new ethers.ContractFactory(contractJson.abi, contractJson.bytecode, wallet);
  const contract = await factory.deploy();

  await contract.waitForDeployment();

  console.log("BlueCarbonRegistry deployed to:", await contract.getAddress());
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
